crystal/src/main/java/crystal/entities/Game.java
package crystal.entities;

import java.sql.Date;

import javax.persistence.Entity;
import javax.persistence.Id;

@Entity
public class Game {
	
	@Id
	private int id;
	protected int rank;
	protected String user;
	protected int totalPoints;
	protected int level;
	protected Date date;
	
	public Game() {
	}
	
	public Game(String user, int points, int level, Date date) {
		this.user = user;
		this.totalPoints = points;
		this.level = level;
		this.date = date;
	}	
	
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getUser() {
		return user;
	}
	public void setUser(String user) {
		this.user = user;
	}
	public int getTotalPoints() {
		return totalPoints;
	}
	public void setTotalPoints(int points) {
		this.totalPoints = points;
	}
	public int getLevel() {
		return level;
	}
	public void setLevel(int level) {
		this.level = level;
	}
	public Date getDate() {
		return date;
	}
	public void setDate(Date date) {
		this.date = date;
	}

	public int getRank() {
		return rank;
	}

	public void setRank(int rank) {
		this.rank = rank;
	}
	
	
	
}

crystal/src/main/java/crystal/model/Block.java
package crystal.model;

public class Block {
	private Colour colour;
	private Block leftNeighbour = null;
	private Block rightNeighbour = null;
	private Block upNeighbour = null;
	private Block downNeighbour = null;
	private boolean visible = true;
	
	public Block(Colour colour) {
		this.colour = colour;
	}
	
	public boolean isClickable(){
		if(!this.visible){
			return false;
		}
		if(leftNeighbourIsSame() || rightNeighbourIsSame()
				|| upNeighbourIsSame() || downNeighbourIsSame()) {
			return true;
		}
		return false;
	}
				
	private boolean leftNeighbourIsSame() {
		if(leftNeighbour != null && leftNeighbour.visible &&
				leftNeighbour.colour == this.colour) {
			return true;
		}
		return false;
	}
	
	private boolean rightNeighbourIsSame() {
		if(rightNeighbour != null && rightNeighbour.visible &&
				rightNeighbour.colour == this.colour) {
			return true;
		}
		return false;
	}
	
	private boolean upNeighbourIsSame() {
		if(upNeighbour != null && upNeighbour.visible &&
				upNeighbour.colour == this.colour) {
			return true;
		}
		return false;
	}
	
	private boolean downNeighbourIsSame() {
		if(downNeighbour != null && downNeighbour.visible &&
				downNeighbour.colour == this.colour) {
			return true;
		}
		return false;
	}
	

	// Getter and setter	
	public Colour getColour() {
		return colour;
	}
	
	public void setColour(Colour colour) {
		this.colour = colour;
	}
	
	public Block getLeftNeighbour() {
		return leftNeighbour;
	}

	public void setLeftNeighbour(Block leftNeighbour) {
		this.leftNeighbour = leftNeighbour;
	}

	public Block getRightNeighbour() {
		return rightNeighbour;
	}

	public void setRightNeighbour(Block rightNeighbour) {
		this.rightNeighbour = rightNeighbour;
	}

	public Block getUpNeighbour() {
		return upNeighbour;
	}

	public void setUpNeighbour(Block upNeighbour) {
		this.upNeighbour = upNeighbour;
	}

	public Block getDownNeighbour() {
		return downNeighbour;
	}

	public void setDownNeighbour(Block downNeighbour) {
		this.downNeighbour = downNeighbour;
	}

	public boolean isVisible() {
		return visible;
	}

	public void setVisible(boolean removed) {
		this.visible = removed;
	}
}

crystal/src/main/java/crystal/model/Board.java
package crystal.model;

import java.util.List;

public class Board {
	public static final int BOARDWIDTH = 30;
	public static final int BOARDHEIGHT = 20;
	public static final int BOARDLENGTH = BOARDWIDTH*BOARDHEIGHT;

	private List<Block> gameBoardBlocks;
	
	public Board(List<Block> gameBoardBlocks) {
		this.gameBoardBlocks = gameBoardBlocks;
	}

	public List<Block> getGameBoard() {
		return gameBoardBlocks;
	}
	
	public void setGameBoard(List<Block> gameBoardBlocks) {
		this.gameBoardBlocks = gameBoardBlocks;
	}
	
	public int getBoardWidth() {
		return BOARDWIDTH;
	}
	
}

crystal/src/main/java/crystal/model/Colour.java
package crystal.model;

import java.util.Random;

public enum Colour {
	RED(),
	BLUE(),
	YELLOW(),
	GREEN(),
	ORANGE();
	
	private static final Colour[] VALUES = values();
	private static final int LENGTH = VALUES.length;
	private static Random randomizer = new Random();

	public static Colour getRandomColour() {
		return VALUES[randomizer.nextInt(LENGTH)];
	}
	
	public String getStyle(){
		return this.name();
	}
}

crystal/src/main/java/crystal/model/CurrentGame.java
package crystal.model;

import crystal.services.Timer;


public class CurrentGame{
	
	private int currentPoints;
	private Level currentLevel;
	private Timer currentTime;
	private int totalPoints;
	private int currentNumberOfBlocks;
	private Board board;
	private boolean finished;
	
	
	public CurrentGame() {
		this.totalPoints = 0;
		this.currentLevel = Level.LEVEL1;
		this.currentTime = new Timer();
	}	

	public boolean wins(){
		if(this.currentPoints>=this.currentLevel.getGoal()){
			return true;
		}
		return false;
	}	
	
	//Getter and setter
	
	public Timer getCurrentTime() {
		return currentTime;
	}
	
	public void setCurrentTime(Timer currentTime) {
		this.currentTime = currentTime;
	}
	
	public int getCurrentPoints() {
		return this.currentPoints;
	}
	
	public Level getCurrentLevel() {
		return this.currentLevel;
	}

	public int getCurrentNumberOfBlocks() {
		return currentNumberOfBlocks;
	}

	public Board getBoard() {
		return board;
	}
	
	public void setBoard(Board board) {
		this.board = board;
	}

	public void setCurrentPoints(int currentPoints) {
		this.currentPoints = currentPoints;
	}

	public void setCurrentLevel(Level currentLevel) {
		this.currentLevel = currentLevel;
	}

	public void setCurrentNumberOfBlocks(int currentNumberOfBlocks) {
		this.currentNumberOfBlocks = currentNumberOfBlocks;
	}

	public boolean isFinished() {
		return finished;
	}


	public void setFinished(boolean finished) {
		this.finished = finished;
	}

	public int getTotalPoints() {
		return totalPoints;
	}

	public void setTotalPoints(int totalPoints) {
		this.totalPoints = totalPoints;
	}
}

crystal/src/main/java/crystal/model/Level.java
package crystal.model;

public enum Level {
//	LEVEL0(2, 1000),
	LEVEL1(3, 1500),
	LEVEL2(3, 2000),
	LEVEL3(4, 1200),
	LEVEL4(4, 1500),
	LEVEL5(5, 1000);
	
	private int colourCount;
	private int goal;
	
	private Level(int colourCount, int goal){
		this.colourCount = colourCount;
		this.goal = goal;
	}
	
	public String toString() {
		return "Level "+ getLevelNumber();
	}
	
	public int getLevelNumber() {
		return Integer.parseInt(this.name().substring(5));	
	}
	
	public boolean isLastLevel(){
		if(this.getLevelNumber() == Level.values().length){
			return true;
		}
		return false;		
	}
	
	public int getGoal() {
		return this.goal;
	}

	public int getColourCount() {
		return colourCount;
	}
}

crystal/src/main/java/crystal/controller/GameController.java
package crystal.controller;

import java.io.Serializable;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import org.primefaces.context.RequestContext;

import crystal.model.Block;
import crystal.model.CurrentGame;
import crystal.model.Level;
import crystal.services.BlockMover;
import crystal.services.BlockRemover;
import crystal.services.BoardSetter;
import crystal.services.GameStatusUpdater;

@ManagedBean
@SessionScoped
public class GameController implements Serializable {
	private static final long serialVersionUID = -8948714689297825121L;
	private static final String LEVELNAME = "Level ";
	public static final String FORCEPAGEREDIRECT = "?faces-redirect=true";
	
	private CurrentGame game;
	private BoardSetter boardSetter;
	private BlockRemover remover;
	private BlockMover mover;
	private GameStatusUpdater statusUpdater;
	private boolean levelGoalPopupVisible;
	
	
	@PostConstruct
	public void init() {
		createNewGame();	
	}
	
	private void createNewGame(){
		game = new CurrentGame();
		this.boardSetter = new BoardSetter();
		game.setBoard(boardSetter.initBoard(game.getCurrentLevel()));
		this.statusUpdater = new GameStatusUpdater(game);
		statusUpdater.setStatusOfLevel();
		this.levelGoalPopupVisible = true;
	}
	
	public String goToGamePage() {
		createNewGame();
		return "game"+FORCEPAGEREDIRECT;
	}
	
	
	public String cancelGame(){
		if(game.getCurrentLevel() != Level.LEVEL1) {
			int previousLevelNumber = game.getCurrentLevel().getLevelNumber()-1;
			game.setCurrentLevel(Level.valueOf("LEVEL" + previousLevelNumber));
			return "finalResult"+FORCEPAGEREDIRECT;
		}
		return "noFinishedLevel" + FORCEPAGEREDIRECT;
	}
	
	public String goToIndex() {
		return "index"+FORCEPAGEREDIRECT;
	}
	
	public String startNewLevel(){
		statusUpdater.setStatusOfLevel();
		statusUpdater.incrementLevel();
		this.game.setBoard(boardSetter.initBoard(this.game.getCurrentLevel()));
		this.levelGoalPopupVisible = true;
		return "game"+FORCEPAGEREDIRECT;
	}
	
	public void onClick(Block block){
		if(block.isClickable()){
			remover = new BlockRemover();
			int removedBlocks = remover.removeSameColouredNeighboursOf(block);
			mover = new BlockMover(game.getBoard().getGameBoard());
			mover.moveBlocksDown();
			mover.condenseBoard();
			statusUpdater.updatePoints(removedBlocks);
			statusUpdater.updateBlockCount(removedBlocks);
			if(!checkMovesPossible()){
				statusUpdater.finishLevel();
				RequestContext.getCurrentInstance().execute("gameFinished.show()");
			}
		}		
	}
	
	private boolean checkMovesPossible(){
		for (Block block : this.game.getBoard().getGameBoard()) {
			if(block.isClickable()){
				return true;
			}
		}
		return false;
	}	

	public String hideLevelGoalPopup() {
		this.levelGoalPopupVisible = false;
		return "game"+FORCEPAGEREDIRECT;
	}
	
	public String goToResult() {
		if(!this.game.wins() || this.game.getCurrentLevel().isLastLevel()){
			return "finalResult" +FORCEPAGEREDIRECT;
		}
		return "levelResult" +FORCEPAGEREDIRECT;
	}

	public String returnPreviousLevelName(){
		int levelNumber = this.game.getCurrentLevel().getLevelNumber();
		return LEVELNAME + (levelNumber-1);
	}	
	
	public String returnNextLevelName() {
		int levelNumber = this.game.getCurrentLevel().getLevelNumber();
		return LEVELNAME + (levelNumber+1);
	}
	
	
	// Getter and Setter
	
	public boolean getLevelGoalPopupVisible() {
		return levelGoalPopupVisible;
	}

	public CurrentGame getGame() {
		return game;
	}
}

crystal/src/main/webapp/finalResult.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"> 

<h:head>
	<title>Endergebnis</title>
	<link rel="stylesheet" type="text/css" href="resources/css/GeneralLayout.css" />
	<link rel="stylesheet" type="text/css" href="resources/css/Button.css" />
	<link rel="stylesheet" type="text/css" href="resources/css/Popup.css" />
</h:head> 
<body> 
<div id="body">
	<h:form id="afterGame">
		<h1>Herzlichen Glückwunsch</h1>
		<div class="center-text">
			<span class="big-text overlay">
			Du hast 
			<h:outputText value="#{gameController.game.currentLevel.toString()}" />
			<h:outputText value=" abgeschlossen und insgesamt #{gameController.game.totalPoints} Punkte erreicht." />
			</span>
		</div>
		<div class="center-text">
			<p:commandButton value="In Rangliste eintragen" styleClass="button" action="saveGame?faces-redirect=true"/>
			<p:commandButton value="Zur Startseite" onclick="PF('dialog').show();" styleClass="button"/>
		</div>
	</h:form>

	<p:dialog id="popupNewGame" modal="true" widgetVar="dialog">
		<h:form>
			<h:outputText value="Willst du ohne speichern neu starten?" />
			<div class="commitButtons">
				<p:commandButton action="#{gameController.goToIndex()}" value="Ja"/>
				<p:commandButton value="Nein" onclick="hide();">
				</p:commandButton>
			</div>
		</h:form>
	</p:dialog>
</div>
</body> 
</html>

crystal/src/main/webapp/game.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"> 

<h:head>
	<title>Spiel</title>
	<link rel="stylesheet" type="text/css" href="resources/css/GeneralLayout.css" />
	<link rel="stylesheet" type="text/css" href="resources/css/TwoColumnLayout.css" />
	<link rel="stylesheet" type="text/css" href="resources/css/Header.css" />	
	<link rel="stylesheet" type="text/css" href="resources/css/Game.css" />
	<link rel="stylesheet" type="text/css" href="resources/css/Button.css" />
	<link rel="stylesheet" type="text/css" href="resources/css/Popup.css" />	
</h:head> 
<h:body> 
	
	<p:dialog id="popupLevelGoal" modal="true" widgetVar="popupLevelGoal" rendered="#{gameController.levelGoalPopupVisible}" visible="#{gameController.levelGoalPopupVisible}">
		<h:form id="formLevelGoal">
			<h3>Level-Ziel</h3>			
			<div>
				<h:outputText value="Erreiche #{gameController.game.currentLevel.goal} Punkte" />
			</div>
			<p:commandButton styleClass="commitButton" value="Start" actionListener="#{gameController.hideLevelGoalPopup()}" onclick="PF('poll').start();PF('popupLevelGoal').hide();"/>
		</h:form>
	</p:dialog>
	
	<div id="header">
		<span class="positioned-left">
			<h:outputText value="#{gameController.game.currentLevel.toString()}" />
		</span>
		<span class="page-right">
			<h:outputText value="Gesamtpunktzahl: #{gameController.game.totalPoints}" />
		</span>
	</div>

	<div class="game-page-left">
		<h2>Dein Spielstand</h2>
		
		<div class="game-message-container">
			<div class="game-standings-float-left">
				<div class="points">Punkte: </div>
				<div>Blöcke: </div>
				<div>Zeit: </div>
			</div>
			<div class="game-standings-float-right">
				<div id="points">
					<h:outputText id="currentPoints" value="#{gameController.game.currentPoints}/#{gameController.game.currentLevel.goal}" />
				</div>
				<div id="blocks">
					<h:outputText id="currentBlocks" value="#{gameController.game.currentNumberOfBlocks}" />			
				</div>
				<div id="time">
					<h:form>
						<h:outputText id="currentTime" value="#{gameController.game.currentTime.timeToMinutes()}" />  
      					<p:poll widgetVar="poll" autoStart="#{!gameController.levelGoalPopupVisible}" interval="1" listener="#{gameController.game.currentTime.incrementTime()}" update="currentTime" />
					</h:form>
				</div>
			</div>
		</div>
		
		<div class="game-message-container">
			Tipp: Wähle ein Objekt mit vielen gleichfarbigen Nachbarn
		</div>
		
	<h:form>
		<p:commandButton value="Abbrechen" onclick="PF('cancelGame').show();" styleClass="button-small"/>
	</h:form>
	</div>

	<div class="shrink-wrap-help">
		<p:dataGrid id="board" value="#{gameController.game.board.gameBoard}" var="block" columns="#{gameController.game.board.boardWidth}" >
			<p:commandButton id="game-block" value="" actionListener="#{gameController.onClick(block)}" update="board,:currentPoints,:currentBlocks,:popupGameFinished"
				styleClass="button-game #{block.colour.style} visible-#{block.visible}" disabled="#{!block.visible}"/>
		</p:dataGrid>
	</div>
	
	<p:dialog id="popupCancelGame" modal="true" widgetVar="cancelGame" onShow="PF('poll').stop();">
		<h:form>
			<h:outputText value="Willst du das Spiel wirklich beenden?" />
			<div class="commitButtons">
				<p:commandButton action="#{gameController.cancelGame()}" value="Ja"/>
				<p:commandButton value="Nein" onclick="PF('poll').start();PF('cancelGame').hide();"/>
			</div>
		</h:form>
	</p:dialog>
	
	<p:dialog id="popupSessionTimeout" modal="true" widgetVar="sessionTimeout" onShow="PF('poll').stop();" closable="false">
		<h:form>
			<div class="big-text center-text">Session abgelaufen</div>
			<div class="center-text">Das Spiel musste leider abgebrochen werden.</div>
			<div class="commitButtons">
				<p:commandButton action="index?faces-redirect=true" value="Zur Startseite"/>
			</div>
		</h:form>
	</p:dialog>
	
	<p:dialog id="popupGameFinished" modal="true" widgetVar="gameFinished" onShow="PF('poll').stop();">
		<h:form>
			<h:panelGroup styleClass="center-text" rendered="#{gameController.game.wins()}">
				<div class="big-text">Gewonnen!</div>
				<div><h:outputText rendered="#{gameController.game.currentNumberOfBlocks==0}" value="Board abgeräumt: Du erhälst 200 Bonuspunkte!" /></div>
			</h:panelGroup>			
			<h:outputText value="Spiel zu Ende." rendered="#{!gameController.game.wins()}"/>
			<div class="commitButtons">
				<p:commandButton value="OK" action="#{gameController.goToResult()}" />
			</div>
		</h:form>
	</p:dialog>
</h:body> 
</html>

crystal/src/main/webapp/index.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"> 

<h:head>
	<title>Introseite</title>
	<link rel="stylesheet" type="text/css" href="resources/css/GeneralLayout.css" />
	<link rel="stylesheet" type="text/css" href="resources/css/Button.css" />
</h:head> 
<body> 
<div id="body">
	<h1>Willkommen beim Löschspiel</h1>
	<h:form>
		<p:commandButton id="new-game-button" value="Neues Spiel" action="#{gameController.goToGamePage()}" styleClass="button-index"/>
		<p:commandButton id="go-to-ranking-button" value="Rangliste" action="ranking?faces-redirect=true" styleClass="button-index" />
		<p:commandButton id="go-to-instructions-button" value="Anleitung" action="instructions?faces-redirect=true" styleClass="button-index" />
	</h:form>	
</div>
</body> 
</html>

crystal/src/main/webapp/instructions.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"> 

<h:head>
	<title>Anleitung</title>
	<link rel="stylesheet" type="text/css" href="resources/css/GeneralLayout.css" />
	<link rel="stylesheet" type="text/css" href="resources/css/TwoColumnLayout.css" />
	<link rel="stylesheet" type="text/css" href="resources/css/Button.css" />
</h:head> 
<body> 
	<h1>Anleitung</h1>
	
	<div class="body">
		<div class="page-left instructions-page">
			<h2>Spielregeln</h2>
				<div class="instructions-container">
					Das Spielfeld besteht aus vielen farbigen Blöcken. Ziel das Spiels ist es Gruppierungen von gleichfarbigen Blöcken anzuklicken und somit zu löschen. Es können nur Blöcke gelöscht werden, die mindestens einen gleichfarbigen Nachbarn haben. Je mehr Blöcke in einer Gruppierung gelöscht werden, umso mehr Punkte erhält der Spieler.
					<br/>Das Spiel ist zu Ende, wenn keine Züge mehr möglich sind.
				</div>
		</div>

		<div class="page-right instructions-page">
			<h2>Levelziele im Überblick</h2>
			<div class="container instructions-container">
				<div>
					Um ein Level aufzusteigen benötigt man in ...<br />
					<b>Level 1:</b> 1000 Punkte bei 3 Farben<br />
					<b>Level 2:</b> 1500 Punkte bei 3 Farben<br />
					<b>Level 3:</b> 1000 Punkte bei 4 Farben<br />
					<b>Level 4:</b> 1500 Punkte bei 4 Farben<br />
					<b>Level 5:</b> 1500 Punkte bei 5 Farben<br />					
				</div>
			</div>
		</div>	
	</div>
		<h:form styleClass="center-text">
			<p:commandButton value="zurück" action="index?faces-redirect=true" styleClass="button-instruction"/>
		</h:form>
</body> 
</html>

crystal/src/main/webapp/levelResult.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"> 

<h:head>
	<title>Zwischenergebnis</title>
	<link rel="stylesheet" type="text/css" href="resources/css/GeneralLayout.css" />
	<link rel="stylesheet" type="text/css" href="resources/css/TwoColumnLayout.css" />
	<link rel="stylesheet" type="text/css" href="resources/css/Header.css" />	
	<link rel="stylesheet" type="text/css" href="resources/css/Button.css" />
	<link rel="stylesheet" type="text/css" href="resources/css/Popup.css" />	
</h:head> 
<body>
	<div id="header">
		<span class="positioned-left">
			<h:outputText value="#{gameController.returnNextLevelName()}" />
		</span>
		<span class="page-right">
			<h:outputText value="Gesamtpunktzahl: #{gameController.game.totalPoints}" />
		</span>
	</div>
	
	<div class="shrink-wrap-help-container" id="body">
		<div class="center-text big-text overlay shrink-wrap-help">
			<h1>Glückwunsch</h1>
			<div><h:outputText value="Du hast #{gameController.game.currentPoints} Punkte in #{gameController.game.currentLevel.toString()} erreicht" /></div>
			<div>und steigst ein Level auf!</div>
		</div>
	</div>

	
	<div class="center-text">
		<p:commandButton value="Weiter" action="#{gameController.startNewLevel()}" styleClass="button-small button-level-result"/>
		<p:commandButton value="In Rangliste eintragen" onclick="PF('saveGame').show();" styleClass="button-small button-level-result"/>
		<p:commandButton value="Beenden" onclick="PF('cancelGame').show()" styleClass="button-small button-level-result"/>
	</div>
	
	<p:dialog id="popupCancelGame" modal="true" widgetVar="cancelGame">
		<h:form>
			<h:outputText value="Willst du das Spiel wirklich ohne zu speichern beenden?" />
			<div class="commitButtons">
				<p:commandButton action="#{gameController.goToIndex()}" value="Ja"/>
				<p:commandButton value="Nein" onclick="hide();"/>
			</div>
		</h:form>
	</p:dialog>
	
	<p:dialog id="popupSaveGame" modal="true" widgetVar="saveGame">
		<h:form>
			<h:outputText value="Wenn du dich in die Rangliste einträgst, kannst du dieses Spiel nicht fortsetzen." />
			<div class="commitButtons">
				<p:commandButton action="saveGame?faces-redirect=true" value="Eintragen"/>
				<p:commandButton value="Weiter spielen" onclick="hide();"/>
			</div>
		</h:form>
	</p:dialog>
</body>
</html>

crystal/src/main/webapp/noFinishedLevel.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"> 

<h:head>
	<title>Spiel</title>
	<link rel="stylesheet" type="text/css" href="resources/css/GeneralLayout.css" />
	<link rel="stylesheet" type="text/css" href="resources/css/Header.css" />	
	<link rel="stylesheet" type="text/css" href="resources/css/Button.css" />
</h:head> 
<h:body> 
	
	<div id="body" class="shrink-wrap-help-container">
		<div class="center-text overlay shrink-wrap-help">
			<h1>Spiel beendet</h1>
			<div class="big-text">Auf ein Neues!</div>
			<h:form>
				<p:commandButton styleClass="button" action="#{gameController.goToIndex()}" value="Startseite"/>
			</h:form>
		</div>
	</div>
</h:body>
</html>